version: '3'
services:
  flask_quickstart_mysql:
    image: mysql:8.0
    container_name: flask_quickstart_mysql
    restart: always
    ports:
      - '33060:3306'
    environment:
      MYSQL_ROOT_PASSWORD: MySQL@root123456
      MYSQL_USER: flask_quickstart
      MYSQL_PASSWORD: MySQL@flask_quickstart123456
      MYSQL_DATABASE: flask_quickstart
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./sql:/docker-entrypoint-initdb.d
      - /project_home/mysql:/var/lib/mysql
